#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runhfsc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runhfsc-web
  template:
    metadata:
      labels:
        app: runhfsc-web
    spec:
      containers:
        - name: main
          image: localhost:5000/runhfsc-web:0.0.5
          resources:
            requests:
              memory: "50Mi"
              cpu: "0.1"
          env:
            - name: RUNHFSC_CONFIG_JSON_FILE
              value: /fabric/appcfg/runhfsc.json
          volumeMounts:
            - name: fabricid
              mountPath: /fabric/application/ids
            - name: connectionprofile
              mountPath: /fabric/application/cp
            - name: runhfsccfg
              mountPath: /fabric/appcfg
      volumes:
        - name: runhfsccfg
          configMap:
            name: app-runhfsc-v1-config
        - name: fabricid
          configMap:
            name: app-fabric-ids-v2-map
        - name: connectionprofile
          configMap:
            name: app-org1peer-endpoint
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-runhfsc-v1-config
data: 
  runhfsc.json : | 
    {
        "default": {
            "type": "gateway",
            "tlsEnabled": true,
            "identity": {
                "idFile":"/fabric/application/ids/asset-transfer_appid.json",
                "mspId":"Org1MSP"
            },
            "endpoint": {
                "connectionProfileFile":"/fabric/application/cp/profile.json"
            },
            "defaultChannel":"mychannel",
            "defaultContract":"asset-transfer"
        }
    }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
  labels:
    app: runhfsc-web
  name:  runhfsc-web
spec:
  ingressClassName: nginx
  rules:
    - host: runhfsc-web.localho.st
      http:
        paths:
          - backend:
              service:
                name: runhfsc-web
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
---
apiVersion: v1
kind: Service
metadata:
  name: runhfsc-web
spec:
  ports:
    - name: http
      port: 4000
      protocol: TCP
  selector:
    app:  runhfsc-web

